apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


labels:
- pairs:
    env: dev
resources:
- ../../base

secretGenerator:
- literals:
  - username=<username>
  - password=<password>
  name: mongodb-secret
  type: Opaque
  options:
    annotations:
      avp.kubernetes.io/path: /credentials/app