apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mongo-statefulset.yaml
- mongo-service.yaml
- mongo-secret.yaml
labels:
- includeSelectors: false
  pairs:
    project: votingapp