apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-votingapp
  namespace: argocd
  metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: voting-app
  source:
    repoURL: https://github.com/Sreeju1992/Voting-app.git
    targetRevision: HEAD
    path: ./declarative/manifests/mongodb-votingapp
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
       prune: true  
       selfHeal: true